version: '2.4'

services:
    mssql:
        image: mcr.microsoft.com/mssql/server:latest
        container_name: setp_mssql
        hostname: setp_mssql
        ports:
            - "1433:1433"
        environment: 
            SA_PASSWORD: Sch12345!
            ACCEPT_EULA: "Y"
        volumes: 
            - "mssqldata:/var/lib/mssql"
        networks:
            - setp_network

volumes:
    mssqldata:       

networks: 
    setp_network: